### ISSUE TITLE
Transparent Background and Window Resizing

### ISSUE THREAD

**Issue by nRanzo** [ZackeryRSmith/bongocat-plus#60]
Hey would it be possible to add a Transparent Background option instead of seeing the blank window? Also it would be nice to have a smaller bongo image displayed on the screen, because now it's currently taking a big amount of screen' space. Thanks.

**Comment by ZackeryRSmith** [comment]
As far as setting the screen size it is possible by modifying the `src/test.lua`. Just not pretty in any way. I will implement something that allows for simple scaling today or tomorrow. This also ties into #47 so it needed to be implemented at some point.

As for the transparent background option, it's not possible without using system apis. Which I don't mind implementing but may take a bit of time for it to be integrated well.

Give me a few days and your feature requests should be implemented!

**Comment by nRanzo** [comment]
Nice, thank you very much. I also understand the problem in making the background transparent: it's not immediate effectively.

**Comment by ZackeryRSmith** [comment]
So far the best way to get transparency would be to set the windows background to green then chroma key the window in OBS or something. But it would be much better for it to be directly integrated.

**Comment by nRanzo** [comment]
Yeah I also thought so, exactly like using a green screen, but it would be so bad in terms of cpu usage (and memory because of OBS or VSDC) on older machines - even if this solution would be free.

**Comment by ZackeryRSmith** [comment]
Upon a lot of research: It's not possible on Linux. This is just a limitation of SFML itself, and would require me to create a custom fork of SFML to allow it to be done. On Windows however it seems to be possible. Sadly the green screen is just going to be an issue for Linux users :(

You may now resize a window properly in the lua code `BongoWindow.create(200, 200)`

**Comment by ZackeryRSmith** [comment]
Feel free to point anything out you think that should be changed. Note that I haven't actually implemented the window transparency as only supporting Windows feels a bit wrong to me...

Maybe a function for scaling the window down keeping it's aspect ratio?

**Comment by nRanzo** [comment]
I dunno man, consider that I usually work with java. In that case the project could be opened as a java file and then be resized simply as wanted with no effort. I'll study any change we can make to add the resizing feature by keeping all code in C++.

Currently the projects works also with my updated MacBook by the way.

**Comment by ZackeryRSmith** [comment]
Hey, thanks for letting me know. I'm glad it still works on Mac! Sorry for the delay in getting back to you.

Window transparency actually consumes quite a bit of resources. More so than chroma keying from my tests. It requires some extra processing power to render the transparent effect each time a window is moved or z-order changed.

Maybe some more testing should be done on my part. But I'll likely have to modify the SFML source code 🤔
